package wiki.qd.shopmall.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import wiki.qd.shopmall.entity.CommonInfo;
import wiki.qd.shopmall.entity.UserInfo;

import wiki.qd.shopmall.db.CommonInfoDao;
import wiki.qd.shopmall.db.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig commonInfoDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final CommonInfoDao commonInfoDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        commonInfoDaoConfig = daoConfigMap.get(CommonInfoDao.class).clone();
        commonInfoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        commonInfoDao = new CommonInfoDao(commonInfoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(CommonInfo.class, commonInfoDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        commonInfoDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public CommonInfoDao getCommonInfoDao() {
        return commonInfoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
