package wiki.qd.newshop.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import wiki.qd.newshop.entity.UserInfo;
import wiki.qd.newshop.entity.CommonInfo;

import wiki.qd.newshop.db.UserInfoDao;
import wiki.qd.newshop.db.CommonInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig commonInfoDaoConfig;

    private final UserInfoDao userInfoDao;
    private final CommonInfoDao commonInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        commonInfoDaoConfig = daoConfigMap.get(CommonInfoDao.class).clone();
        commonInfoDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        commonInfoDao = new CommonInfoDao(commonInfoDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(CommonInfo.class, commonInfoDao);
    }
    
    public void clear() {
        userInfoDaoConfig.clearIdentityScope();
        commonInfoDaoConfig.clearIdentityScope();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public CommonInfoDao getCommonInfoDao() {
        return commonInfoDao;
    }

}
